/*******************************************************************************
*
*  (C) COPYRIGHT AUTHORS, 2025
*
*  TITLE:       FUZZ_DATA.H
*
*  VERSION:     2.00
*
*  DATE:        05 Jul 2025
*
*  Fuzzing data constants and ReactOS syscall database.
*
*  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
*  ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED
*  TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
*  PARTICULAR PURPOSE.
*
*******************************************************************************/

#define FUZZDATA_COUNT 18
static const DWORD FuzzData[FUZZDATA_COUNT] = {
    0x00000000,          // NULL
    0x00000001,          // Minimum valid handle/pointer value
    0x0000DEAD,          // Random recognizable pattern
    0x80000000,          // Kernel/user space boundary for 32-bit systems
    0x7FFEFFFF,          // High user address (32-bit)
    0x7FFFFFFF,          // User space limit (signed max)
    0x80000001,          // Kernel/user space boundary + 1
    0xFFFF0800,          // Typical kernel address range start (truncated)
    0xFFFFF780,          // Common Windows kernel address (truncated)
    0xFFFFF800,          // Windows kernel space base (truncated)
    0xFFFFF801,          // Windows kernel space base + 1 (truncated)
    0xFFFFFFFD,          // NTSTATUS: STATUS_UNSUCCESSFUL constant (-3)
    0xFFFFFFFC,          // NTSTATUS: STATUS_INVALID_HANDLE constant (-4)
    0xC0000001,          // NTSTATUS: STATUS_UNSUCCESSFUL mask
    0xFFFFFFFF,          // All bits set (-1)/INVALID_HANDLE_VALUE
    0xBAADF00D,          // Sentinel value (easily recognizable)
    0x41414141,          // ASCII "AAAA" (buffer overflow detection)
    0xCDCDCDCD           // Uninitialized memory pattern
};

#define FUZZADDR_COUNT 6
static const DWORD FuzzAddrData[FUZZADDR_COUNT] = {
    0x0000F00D,          // Reserved area near NULL
    0x7FFE0000,          // Shared user data page
    0x7FFE0030,          // Specific shared user data address (KUSER_SHARED_DATA.SystemTime)
    0xFFFFF780,          // HAL heap base (truncated)
    0xDEADBEEF,          // Pattern
    0x00000000           // NULL address
};

#define FUZZHANDLE_COUNT 8
static const DWORD FuzzHandleData[FUZZHANDLE_COUNT] = {
    0x00000000,          // NULL handle
    0x00000004,          // Standard handle value (stdin)
    0xFFFFFFFC,          // Almost INVALID_HANDLE_VALUE
    0xFFFFFFFF,          // INVALID_HANDLE_VALUE
    0x00000FFF,          // Low handle value
    0x11111111,          // "Typical" handle pattern
    0x00000014,          // Common NT handle pattern
    0x01234567           // Sequential pattern handle value
};

#define FUZZSTATUS_COUNT 6
static const DWORD FuzzStatusData[FUZZSTATUS_COUNT] = {
    0xC0000000,          // Generic failure bit
    0xC0000001,          // STATUS_UNSUCCESSFUL
    0xC0000008,          // STATUS_INVALID_HANDLE
    0xC0000005,          // STATUS_ACCESS_VIOLATION
    0xC0000022,          // STATUS_ACCESS_DENIED
    0xFFFFFFFF           // All bits set
};

#define FUZZACCESS_COUNT 8
static const DWORD FuzzAccessData[FUZZACCESS_COUNT] = {
    0x00000000,          // No access
    0x00000001,          // FILE_READ_DATA/PROCESS_TERMINATE
    0x10000000,          // GENERIC_READ
    0x20000000,          // GENERIC_WRITE
    0x80000000,          // GENERIC_ALL
    0x000F0000,          // STANDARD_RIGHTS_REQUIRED
    0x001F0000,          // STANDARD_RIGHTS_ALL
    0xFFFFFFFF           // All access
};

#define FUZZATTR_COUNT 6
static const DWORD FuzzAttrData[FUZZATTR_COUNT] = {
    0x00000001,          // OBJ_INHERIT
    0x00000002,          // OBJ_PERMANENT
    0x00000004,          // OBJ_EXCLUSIVE
    0x00000008,          // OBJ_CASE_INSENSITIVE
    0x00000100,          // OBJ_KERNEL_HANDLE
    0x00000400           // OBJ_IGNORE_IMPERSONATED_DEVICEMAP
};

#define FUZZBUFSIZE_COUNT 7
static const DWORD FuzzBufSizeData[FUZZBUFSIZE_COUNT] = {
    0x00000000,          // Zero size buffer
    0x00000001,          // 1 byte - too small for most structures
    0x00000004,          // 4 bytes - sizeof(ULONG)
    0x00000008,          // 8 bytes
    0x00000100,          // 256 bytes
    0x00001000,          // 4K - page size
    0x001FFFFF           // ~2MB - large buffer
};

#define FUZZINFOCLASS_COUNT 8
static const DWORD FuzzInfoClassData[FUZZINFOCLASS_COUNT] = {
    0x00000000,          // Class 0 (often BasicInformation)
    0x00000001,          // Class 1 (often FileNameInformation)
    0x00000005,          // Class 5 (ProcessInformation)
    0x0000000A,          // Class 10 (often used)
    0x0000001F,          // Class 31
    0x000000FF,          // Class 255 (boundary)
    0x80000001,          // High bit set
    0xFFFFFFFF           // All bits set
};

#define FUZZTOKEN_COUNT 10
static const DWORD FuzzTokenData[FUZZTOKEN_COUNT] = {
    0x00000000,          // NULL token
    0xFFFFFFFF,          // INVALID_HANDLE_VALUE
    0xC0000001,          // Known bug parameter
    0x00000004,          // Common token handle value
    0x00000008,          // Common token handle value
    0x0000000C,          // Common token handle value
    0x00000010,          // Common token handle value
    0xFFFE0000,          // High word pattern
    0x8FFFFFFF,          // High bit with lower bits set
    0xDEADBEEF           // Recognizable pattern
};

#define FUZZWIN32_COUNT 10
const DWORD FuzzWin32Data[FUZZWIN32_COUNT] = {
    0x00000000,          // NULL HWND
    0x00000001,          // HWND_DESKTOP
    0xFFFFFFFF,          // HWND_BROADCAST
    0x00000003,          // HWND_MESSAGE
    0x00000005,          // Common HWND value
    0x0000CAFE,          // Random handle value
    0x00010001,          // Valid-looking handle pattern
    0x0000BEEF,          // Truncated invalid handle pattern
    0xFFFF0000,          // High word mask pattern
    0x0000FFFF           // Low word mask pattern
};

#define FUZZGDI_COUNT 6
const DWORD FuzzGdiData[FUZZGDI_COUNT] = {
    0x00000000,          // NULL HDC/HBRUSH/etc
    0x10001000,          // Typical GDI handle value
    0x00000001,          // Stock_DC_Brush or similar
    0xABCDEF12,          // Random but recognizable
    0x00000142,          // HORZRES system metric
    0x80000001           // High bit pattern for handles
};

//
// MACHINE GENERATED FROM MULTIPLE REACTOS FILES.
//
const SYSCALL_PARAM_INFO KnownNtSyscalls[] = {
    {"NtAcceptConnectPort", {ParamTypeOutPtr, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag, ParamTypeAddress, ParamTypeAddress}},
    {"NtAccessCheck", {ParamTypeSecDesc, ParamTypeHandle, ParamTypeAccess, ParamTypeAddress, ParamTypeOutPtr, ParamTypeAddress, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtAccessCheckAndAuditAlarm", {ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeSecDesc, ParamTypeAccess, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtAccessCheckByType", {ParamTypeSecDesc, ParamTypeAddress, ParamTypeHandle, ParamTypeAccess, ParamTypeAddress, ParamTypeFlag, ParamTypeAddress, ParamTypeAddress, ParamTypeOutPtr, ParamTypeAddress, ParamTypeRetLength}},
    {"NtAccessCheckByTypeAndAuditAlarm", {ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeSecDesc, ParamTypeAddress, ParamTypeAccess, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtAccessCheckByTypeResultList", {ParamTypeSecDesc, ParamTypeAddress, ParamTypeHandle, ParamTypeAccess, ParamTypeAddress, ParamTypeFlag, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtAccessCheckByTypeResultListAndAuditAlarm", {ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeSecDesc, ParamTypeAddress, ParamTypeAccess, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtAccessCheckByTypeResultListAndAuditAlarmByHandle", {ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeHandle, ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeSecDesc, ParamTypeAddress, ParamTypeAccess, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtAddAtom", {ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr}},
    {"NtAddBootEntry", {ParamTypeAddress, ParamTypeOutPtr}},
    {"NtAddDriverEntry", {ParamTypeAddress, ParamTypeOutPtr}},
    {"NtAdjustGroupsToken", {ParamTypeToken, ParamTypeFlag, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtAdjustPrivilegesToken", {ParamTypeToken, ParamTypeFlag, ParamTypePrivilege, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtAlertResumeThread", {ParamTypeHandle, ParamTypeRetLength}},
    {"NtAlertThread", {ParamTypeHandle}},
    {"NtAllocateLocallyUniqueId", {ParamTypeOutPtr}},
    {"NtAllocateUserPhysicalPages", {ParamTypeHandle, ParamTypeRetLength, ParamTypeOutPtr}},
    {"NtAllocateUuids", {ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
    {"NtAllocateVirtualMemory", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
    {"NtApphelpCacheControl", {ParamTypeFlag, ParamTypeAddress}},
    {"NtAreMappedFilesTheSame", {ParamTypeAddress, ParamTypeAddress}},
    {"NtAssignProcessToJobObject", {ParamTypeHandle, ParamTypeHandle}},
    {"NtCallbackReturn", {ParamTypeAddress, ParamTypeFlag, ParamTypeStatus}},
    {"NtCancelDeviceWakeupRequest", {ParamTypeHandle}},
    {"NtCancelIoFile", {ParamTypeHandle, ParamTypeStatus}},
    {"NtCancelTimer", {ParamTypeHandle, ParamTypeOutPtr}},
    {"NtClearEvent", {ParamTypeHandle}},
    {"NtClose", {ParamTypeHandle}},
    {"NtCloseObjectAuditAlarm", {ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeFlag}},
    {"NtCompactKeys", {ParamTypeFlag, ParamTypeHandle}},
    {"NtCompareTokens", {ParamTypeToken, ParamTypeToken, ParamTypeOutPtr}},
    {"NtCompleteConnectPort", {ParamTypeHandle}},
    {"NtCompressKey", {ParamTypeHandle}},
    {"NtConnectPort", {ParamTypeOutPtr, ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
    {"NtContinue", {ParamTypeAddress, ParamTypeFlag}},
    {"NtCreateDebugObject", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeFlag}},
    {"NtCreateDirectoryObject", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtCreateEvent", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeFlag, ParamTypeFlag}},
    {"NtCreateEventPair", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtCreateFile", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeStatus, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeBufferSize}},
    {"NtCreateIoCompletion", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeFlag}},
    {"NtCreateJobObject", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtCreateJobSet", {ParamTypeFlag, ParamTypeAddress, ParamTypeFlag}},
    {"NtCreateKey", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeFlag, ParamTypeUnicodeStr, ParamTypeFlag, ParamTypeOutPtr}},
    {"NtCreateKeyedEvent", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeFlag}},
    {"NtCreateMailslotFile", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeStatus, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress}},
    {"NtCreateMutant", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeFlag}},
    {"NtCreateNamedPipeFile", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeStatus, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress}},
    {"NtCreatePagingFile", {ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag}},
    {"NtCreatePort", {ParamTypeOutPtr, ParamTypeObjectAttr, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
    {"NtCreateProcess", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeHandle, ParamTypeFlag, ParamTypeHandle, ParamTypeHandle, ParamTypeHandle}},
    {"NtCreateProcessEx", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeHandle, ParamTypeFlag, ParamTypeHandle, ParamTypeHandle, ParamTypeHandle, ParamTypeFlag}},
    {"NtCreateProfile", {ParamTypeOutPtr, ParamTypeHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
    {"NtCreateSection", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeHandle}},
    {"NtCreateSemaphore", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeFlag, ParamTypeFlag}},
    {"NtCreateSymbolicLinkObject", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeUnicodeStr}},
    {"NtCreateThread", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeHandle, ParamTypeOutPtr, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag}},
    {"NtCreateTimer", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeFlag}},
    {"NtCreateToken", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeFlag, ParamTypeAddress, ParamTypeAddress, ParamTypeSecDesc, ParamTypeAddress, ParamTypePrivilege, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeOutPtr}},
    {"NtCreateWaitablePort", {ParamTypeOutPtr, ParamTypeObjectAttr, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
    {"NtDebugActiveProcess", {ParamTypeHandle, ParamTypeHandle}},
    {"NtDebugContinue", {ParamTypeHandle, ParamTypeClientId, ParamTypeStatus}},
    {"NtDelayExecution", {ParamTypeFlag, ParamTypeTimeout}},
    {"NtDeleteAtom", {ParamTypeFlag}},
    {"NtDeleteBootEntry", {ParamTypeFlag}},
    {"NtDeleteDriverEntry", {ParamTypeFlag}},
    {"NtDeleteFile", {ParamTypeObjectAttr}},
    {"NtDeleteKey", {ParamTypeHandle}},
    {"NtDeleteObjectAuditAlarm", {ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeFlag}},
    {"NtDeleteValueKey", {ParamTypeHandle, ParamTypeUnicodeStr}},
    {"NtDeviceIoControlFile", {ParamTypeHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeFlag, ParamTypeAddress, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeBufferSize}},
    {"NtDisplayString", {ParamTypeUnicodeStr}},
    {"NtDuplicateObject", {ParamTypeHandle, ParamTypeHandle, ParamTypeHandle, ParamTypeOutPtr, ParamTypeAccess, ParamTypeFlag, ParamTypeFlag}},
    {"NtDuplicateToken", {ParamTypeToken, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
    {"NtEnumerateBootEntries", {ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtEnumerateDriverEntries", {ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtEnumerateKey", {ParamTypeHandle, ParamTypeFlag, ParamTypeInfoClass, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeRetLength}},
    {"NtEnumerateSystemEnvironmentValuesEx", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtEnumerateValueKey", {ParamTypeHandle, ParamTypeFlag, ParamTypeInfoClass, ParamTypeKeyValue, ParamTypeBufferSize, ParamTypeRetLength}},
    {"NtExtendSection", {ParamTypeHandle, ParamTypeOutPtr}},
    {"NtFilterToken", {ParamTypeToken, ParamTypeFlag, ParamTypeAddress, ParamTypePrivilege, ParamTypeAddress, ParamTypeOutPtr}},
    {"NtFindAtom", {ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr}},
    {"NtFlushBuffersFile", {ParamTypeHandle, ParamTypeStatus}},
    {"NtFlushInstructionCache", {ParamTypeHandle, ParamTypeAddress, ParamTypeFlag}},
    {"NtFlushKey", {ParamTypeHandle}},
    {"NtFlushVirtualMemory", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeStatus}},
    {"NtFlushWriteBuffer", {ParamTypeGeneral}},
    {"NtFreeUserPhysicalPages", {ParamTypeHandle, ParamTypeRetLength, ParamTypeAddress}},
    {"NtFreeVirtualMemory", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeFlag}},
    {"NtFsControlFile", {ParamTypeHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeFlag, ParamTypeAddress, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeBufferSize}},
    {"NtGetContextThread", {ParamTypeHandle, ParamTypeOutPtr}},
    {"NtGetCurrentProcessorNumber", {ParamTypeGeneral}},
    {"NtGetDevicePowerState", {ParamTypeHandle, ParamTypeOutPtr}},
    {"NtGetPlugPlayEvent", {ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
    {"NtGetWriteWatch", {ParamTypeHandle, ParamTypeFlag, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeOutPtr}},
    {"NtImpersonateAnonymousToken", {ParamTypeToken}},
    {"NtImpersonateClientOfPort", {ParamTypeHandle, ParamTypeAddress}},
    {"NtImpersonateThread", {ParamTypeHandle, ParamTypeHandle, ParamTypeSecDesc}},
    {"NtInitializeRegistry", {ParamTypeFlag}},
    {"NtInitiatePowerAction", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
    {"NtIsProcessInJob", {ParamTypeHandle, ParamTypeHandle}},
    {"NtIsSystemResumeAutomatic", {ParamTypeGeneral}},
    {"NtListenPort", {ParamTypeHandle, ParamTypeOutPtr}},
    {"NtLoadDriver", {ParamTypeUnicodeStr}},
    {"NtLoadKey", {ParamTypeObjectAttr, ParamTypeObjectAttr}},
    {"NtLoadKey2", {ParamTypeObjectAttr, ParamTypeObjectAttr, ParamTypeFlag}},
    {"NtLoadKeyEx", {ParamTypeObjectAttr, ParamTypeObjectAttr, ParamTypeFlag, ParamTypeHandle}},
    {"NtLockFile", {ParamTypeHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
    {"NtLockProductActivationKeys", {ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtLockRegistryKey", {ParamTypeHandle}},
    {"NtLockVirtualMemory", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeFlag}},
    {"NtMakePermanentObject", {ParamTypeHandle}},
    {"NtMakeTemporaryObject", {ParamTypeHandle}},
    {"NtMapUserPhysicalPages", {ParamTypeAddress, ParamTypeFlag, ParamTypeAddress}},
    {"NtMapUserPhysicalPagesScatter", {ParamTypeOutPtr, ParamTypeFlag, ParamTypeAddress}},
    {"NtMapViewOfSection", {ParamTypeHandle, ParamTypeHandle, ParamTypeOutPtr, ParamTypeFlag, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
    {"NtModifyBootEntry", {ParamTypeAddress}},
    {"NtModifyDriverEntry", {ParamTypeAddress}},
    {"NtNotifyChangeDirectoryFile", {ParamTypeHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
    {"NtNotifyChangeKey", {ParamTypeHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeFlag}},
    {"NtNotifyChangeMultipleKeys", {ParamTypeHandle, ParamTypeFlag, ParamTypeObjectAttr, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
    {"NtOpenDirectoryObject", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtOpenEvent", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtOpenEventPair", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtOpenFile", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeStatus, ParamTypeFlag, ParamTypeFlag}},
    {"NtOpenIoCompletion", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtOpenJobObject", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtOpenKey", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtOpenKeyedEvent", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtOpenMutant", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtOpenObjectAuditAlarm", {ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeSecDesc, ParamTypeHandle, ParamTypeAccess, ParamTypeAccess, ParamTypePrivilege, ParamTypeFlag, ParamTypeFlag, ParamTypeRetLength} },
    {"NtOpenProcess", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeClientId}},
    {"NtOpenProcessToken", {ParamTypeHandle, ParamTypeAccess, ParamTypeOutPtr}},
    {"NtOpenProcessTokenEx", {ParamTypeHandle, ParamTypeAccess, ParamTypeFlag, ParamTypeOutPtr}},
    {"NtOpenSection", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtOpenSemaphore", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtOpenSymbolicLinkObject", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtOpenThread", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr, ParamTypeClientId}},
    {"NtOpenThreadToken", {ParamTypeHandle, ParamTypeAccess, ParamTypeFlag, ParamTypeOutPtr}},
    {"NtOpenThreadTokenEx", {ParamTypeHandle, ParamTypeAccess, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
    {"NtOpenTimer", {ParamTypeOutPtr, ParamTypeAccess, ParamTypeObjectAttr}},
    {"NtPlugPlayControl", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
    {"NtPowerInformation", {ParamTypeFlag, ParamTypeAddress, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeBufferSize}},
    {"NtPrivilegeCheck", {ParamTypeToken, ParamTypePrivilege, ParamTypeRetLength}},
    {"NtPrivilegeObjectAuditAlarm", {ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeHandle, ParamTypeAccess, ParamTypePrivilege, ParamTypeFlag}},
    {"NtPrivilegedServiceAuditAlarm", {ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeToken, ParamTypePrivilege, ParamTypeFlag}},
    {"NtProtectVirtualMemory", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeFlag, ParamTypeRetLength}},
    {"NtPulseEvent", {ParamTypeHandle, ParamTypeRetLength}},
    {"NtQueryAttributesFile", {ParamTypeObjectAttr, ParamTypeOutPtr}},
    {"NtQueryBootEntryOrder", {ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtQueryBootOptions", {ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtQueryDebugFilterState", {ParamTypeFlag, ParamTypeFlag}},
    {"NtQueryDefaultLocale", {ParamTypeFlag, ParamTypeOutPtr}},
    {"NtQueryDefaultUILanguage", {ParamTypeOutPtr}},
    {"NtQueryDirectoryFile", {ParamTypeHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeInfoClass, ParamTypeFlag, ParamTypeUnicodeStr, ParamTypeFlag}},
    {"NtQueryDirectoryObject", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtQueryDriverEntryOrder", {ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtQueryEaFile", {ParamTypeHandle, ParamTypeStatus, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeFlag, ParamTypeAddress, ParamTypeBufferSize, ParamTypeAddress, ParamTypeFlag}},
    {"NtQueryEvent", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtQueryFullAttributesFile", {ParamTypeObjectAttr, ParamTypeOutPtr}},
    {"NtQueryInformationAtom", {ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtQueryInformationFile", {ParamTypeHandle, ParamTypeStatus, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeInfoClass}},
    {"NtQueryInformationJobObject", {ParamTypeHandle, ParamTypeInfoClass, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeRetLength}},
    {"NtQueryInformationPort", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtQueryInformationProcess", {ParamTypeHandle, ParamTypeInfoClass, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeRetLength}},
    {"NtQueryInformationThread", {ParamTypeHandle, ParamTypeInfoClass, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeRetLength}},
    {"NtQueryInformationToken", {ParamTypeToken, ParamTypeInfoClass, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeRetLength}},
    {"NtQueryInstallUILanguage", {ParamTypeOutPtr}},
    {"NtQueryIntervalProfile", {ParamTypeHandle, ParamTypeRetLength} },
    {"NtQueryIoCompletion", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtQueryKey", {ParamTypeHandle, ParamTypeInfoClass, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeRetLength}},
    {"NtQueryMultipleValueKey", {ParamTypeHandle, ParamTypeKeyValue, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeRetLength}},
    {"NtQueryMutant", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtQueryObject", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeRetLength}},
    {"NtQueryOpenSubKeys", {ParamTypeObjectAttr, ParamTypeRetLength}},
    {"NtQueryOpenSubKeysEx", {ParamTypeObjectAttr, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtQueryPerformanceCounter", {ParamTypeOutPtr, ParamTypeOutPtr}},
    {"NtQueryPortInformationProcess", {ParamTypeGeneral}},
    {"NtQueryQuotaInformationFile", {ParamTypeHandle, ParamTypeStatus, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeFlag, ParamTypeAddress, ParamTypeBufferSize, ParamTypeRetLength, ParamTypeFlag}},
    {"NtQuerySection", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtQuerySecurityObject", {ParamTypeHandle, ParamTypeFlag, ParamTypeSecDesc, ParamTypeBufferSize, ParamTypeRetLength}},
    {"NtQuerySemaphore", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtQuerySymbolicLinkObject", {ParamTypeHandle, ParamTypeUnicodeStr, ParamTypeRetLength}},
    {"NtQuerySystemEnvironmentValue", {ParamTypeUnicodeStr, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtQuerySystemEnvironmentValueEx", {ParamTypeUnicodeStr, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtQuerySystemInformation", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtQuerySystemTime", {ParamTypeOutPtr}},
    {"NtQueryTimer", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtQueryTimerResolution", {ParamTypeRetLength, ParamTypeRetLength, ParamTypeRetLength}},
    {"NtQueryValueKey", {ParamTypeHandle, ParamTypeUnicodeStr, ParamTypeInfoClass, ParamTypeKeyValue, ParamTypeBufferSize, ParamTypeRetLength}},
    {"NtQueryVirtualMemory", {ParamTypeHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtQueryVolumeInformationFile", {ParamTypeHandle, ParamTypeStatus, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeInfoClass}},
    {"NtQueueApcThread", {ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress}},
    {"NtRaiseException", {ParamTypeAddress, ParamTypeAddress, ParamTypeFlag}},
    {"NtRaiseHardError", {ParamTypeStatus, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeFlag, ParamTypeRetLength}},
    {"NtReadFile", {ParamTypeHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeAddress, ParamTypeRetLength}},
    {"NtReadFileScatter", {ParamTypeHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeAddress, ParamTypeFlag, ParamTypeAddress, ParamTypeRetLength}},
    {"NtReadRequestData", {ParamTypeHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtReadVirtualMemory", {ParamTypeHandle, ParamTypeAddress, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtRegisterThreadTerminatePort", {ParamTypeHandle}},
    {"NtReleaseKeyedEvent", {ParamTypeHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeTimeout}},
    {"NtReleaseMutant", {ParamTypeHandle, ParamTypeRetLength}},
    {"NtReleaseSemaphore", {ParamTypeHandle, ParamTypeFlag, ParamTypeRetLength}},
    {"NtRemoveIoCompletion", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeStatus, ParamTypeTimeout}},
    {"NtRemoveProcessDebug", {ParamTypeHandle, ParamTypeHandle}},
    {"NtRenameKey", {ParamTypeHandle, ParamTypeUnicodeStr}},
    {"NtReplaceKey", {ParamTypeObjectAttr, ParamTypeHandle, ParamTypeObjectAttr}},
    {"NtReplyPort", {ParamTypeHandle, ParamTypeAddress} },
    {"NtReplyWaitReceivePort", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeAddress, ParamTypeOutPtr} },
    {"NtReplyWaitReceivePortEx", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeAddress, ParamTypeOutPtr, ParamTypeTimeout} },
    {"NtReplyWaitReplyPort", {ParamTypeHandle, ParamTypeOutPtr} },
    {"NtRequestDeviceWakeup", {ParamTypeHandle}},
    {"NtRequestPort", {ParamTypeHandle, ParamTypeAddress}},
    {"NtRequestWaitReplyPort", {ParamTypeHandle, ParamTypeAddress, ParamTypeOutPtr}},
    {"NtRequestWakeupLatency", {ParamTypeFlag}},
    {"NtResetEvent", {ParamTypeHandle, ParamTypeRetLength}},
    {"NtResetWriteWatch", {ParamTypeHandle, ParamTypeAddress, ParamTypeFlag}},
    {"NtRestoreKey", {ParamTypeHandle, ParamTypeHandle, ParamTypeFlag}},
    {"NtResumeProcess", {ParamTypeHandle}},
    {"NtResumeThread", {ParamTypeHandle, ParamTypeRetLength}},
    {"NtSaveKey", {ParamTypeHandle, ParamTypeHandle}},
    {"NtSaveKeyEx", {ParamTypeHandle, ParamTypeHandle, ParamTypeFlag}},
    {"NtSaveMergedKeys", {ParamTypeHandle, ParamTypeHandle, ParamTypeHandle}},
    {"NtSecureConnectPort", {ParamTypeOutPtr, ParamTypeUnicodeStr, ParamTypeSecDesc, ParamTypeOutPtr, ParamTypeAddress, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtSetBootEntryOrder", {ParamTypeAddress, ParamTypeAddress}},
    {"NtSetBootOptions", {ParamTypeAddress, ParamTypeFlag}},
    {"NtSetContextThread", {ParamTypeHandle, ParamTypeAddress}},
    {"NtSetDebugFilterState", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
    {"NtSetDefaultHardErrorPort", {ParamTypeHandle}},
    {"NtSetDefaultLocale", {ParamTypeFlag, ParamTypeFlag}},
    {"NtSetDefaultUILanguage", {ParamTypeFlag}},
    {"NtSetDriverEntryOrder", {ParamTypeAddress, ParamTypeAddress}},
    {"NtSetEaFile", {ParamTypeHandle, ParamTypeStatus, ParamTypeAddress, ParamTypeBufferSize}},
    {"NtSetEvent", {ParamTypeHandle, ParamTypeRetLength}},
    {"NtSetEventBoostPriority", {ParamTypeHandle}},
    {"NtSetHighEventPair", {ParamTypeHandle}},
    {"NtSetHighWaitLowEventPair", {ParamTypeHandle}},
    {"NtSetInformationDebugObject", {ParamTypeHandle, ParamTypeFlag, ParamTypeAddress, ParamTypeFlag, ParamTypeRetLength}},
    {"NtSetInformationFile", {ParamTypeHandle, ParamTypeStatus, ParamTypeAddress, ParamTypeBufferSize, ParamTypeInfoClass}},
    {"NtSetInformationJobObject", {ParamTypeHandle, ParamTypeInfoClass, ParamTypeAddress, ParamTypeBufferSize}},
    {"NtSetInformationKey", {ParamTypeHandle, ParamTypeInfoClass, ParamTypeAddress, ParamTypeBufferSize}},
    {"NtSetInformationObject", {ParamTypeHandle, ParamTypeFlag, ParamTypeAddress, ParamTypeFlag}},
    {"NtSetInformationProcess", {ParamTypeHandle, ParamTypeInfoClass, ParamTypeAddress, ParamTypeBufferSize}},
    {"NtSetInformationThread", {ParamTypeHandle, ParamTypeInfoClass, ParamTypeAddress, ParamTypeBufferSize}},
    {"NtSetInformationToken", {ParamTypeToken, ParamTypeInfoClass, ParamTypeAddress, ParamTypeBufferSize}},
    {"NtSetIntervalProfile", {ParamTypeFlag, ParamTypeFlag}},
    {"NtSetIoCompletion", {ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeFlag}},
    {"NtSetLdtEntries", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag} },
    {"NtSetLowEventPair", {ParamTypeHandle}},
    {"NtSetLowWaitHighEventPair", {ParamTypeHandle}},
    {"NtSetQuotaInformationFile", {ParamTypeHandle, ParamTypeStatus, ParamTypeAddress, ParamTypeBufferSize}},
    {"NtSetSecurityObject", {ParamTypeHandle, ParamTypeFlag, ParamTypeSecDesc}},
    {"NtSetSystemEnvironmentValue", {ParamTypeUnicodeStr, ParamTypeUnicodeStr}},
    {"NtSetSystemEnvironmentValueEx", {ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeRetLength, ParamTypeFlag, ParamTypeFlag}},
    {"NtSetSystemInformation", {ParamTypeFlag, ParamTypeAddress, ParamTypeFlag}},
    {"NtSetSystemPowerState", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
    {"NtSetSystemTime", {ParamTypeAddress, ParamTypeRetLength}},
    {"NtSetThreadExecutionState", {ParamTypeFlag, ParamTypeRetLength}},
    {"NtSetTimer", {ParamTypeHandle, ParamTypeTimeout, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag, ParamTypeAddress, ParamTypeRetLength}},
    {"NtSetTimerResolution", {ParamTypeFlag, ParamTypeFlag, ParamTypeRetLength}},
    {"NtSetUuidSeed", {ParamTypeAddress}},
    {"NtSetValueKey", {ParamTypeHandle, ParamTypeUnicodeStr, ParamTypeFlag, ParamTypeFlag, ParamTypeKeyValue, ParamTypeBufferSize}},
    {"NtSetVolumeInformationFile", {ParamTypeHandle, ParamTypeStatus, ParamTypeAddress, ParamTypeBufferSize, ParamTypeInfoClass}},
    {"NtShutdownSystem", {ParamTypeFlag}},
    {"NtSignalAndWaitForSingleObject", {ParamTypeHandle, ParamTypeHandle, ParamTypeFlag, ParamTypeTimeout}},
    {"NtStartProfile", {ParamTypeHandle}},
    {"NtStopProfile", {ParamTypeHandle}},
    {"NtSuspendProcess", {ParamTypeHandle}},
    {"NtSuspendThread", {ParamTypeHandle, ParamTypeRetLength}},
    {"NtSystemDebugControl", {ParamTypeFlag, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
    {"NtTerminateJobObject", {ParamTypeHandle, ParamTypeStatus}},
    {"NtTerminateProcess", {ParamTypeHandle, ParamTypeStatus}},
    {"NtTerminateThread", {ParamTypeHandle, ParamTypeStatus}},
    {"NtTestAlert", {ParamTypeGeneral}},
    {"NtTraceEvent", {ParamTypeHandle, ParamTypeFlag, ParamTypeBufferSize, ParamTypeAddress}},
    {"NtTranslateFilePath", {ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength}},
    {"NtUnloadDriver", {ParamTypeUnicodeStr}},
    {"NtUnloadKey", {ParamTypeObjectAttr}},
    {"NtUnloadKey2", {ParamTypeObjectAttr, ParamTypeFlag}},
    {"NtUnloadKeyEx", {ParamTypeObjectAttr, ParamTypeHandle}},
    {"NtUnlockFile", {ParamTypeHandle, ParamTypeStatus, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag}},
    {"NtUnlockVirtualMemory", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeFlag}},
    {"NtUnmapViewOfSection", {ParamTypeHandle, ParamTypeAddress}},
    {"NtVdmControl", {ParamTypeFlag, ParamTypeAddress}},
    {"NtWaitForDebugEvent", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeTimeout}},
    {"NtWaitForKeyedEvent", {ParamTypeHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeTimeout}},
    {"NtWaitForMultipleObjects", {ParamTypeFlag, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeTimeout}},
    {"NtWaitForMultipleObjects32", {ParamTypeFlag, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeTimeout}},
    {"NtWaitForSingleObject", {ParamTypeHandle, ParamTypeFlag, ParamTypeTimeout}},
    {"NtWaitHighEventPair", {ParamTypeHandle}},
    {"NtWaitLowEventPair", {ParamTypeHandle}},
    {"NtWriteFile", {ParamTypeHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeAddress, ParamTypeBufferSize, ParamTypeAddress, ParamTypeRetLength}},
    {"NtWriteFileGather", {ParamTypeHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeStatus, ParamTypeAddress, ParamTypeFlag, ParamTypeAddress, ParamTypeRetLength}},
    {"NtWriteRequestData", {ParamTypeHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeAddress, ParamTypeFlag, ParamTypeRetLength}},
    {"NtWriteVirtualMemory", {ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag, ParamTypeRetLength}},
    {"NtYieldExecution", {ParamTypeGeneral}},
    // Terminator
    {NULL, {0}}
};

const SYSCALL_PARAM_INFO KnownWin32kSyscalls[] = {
   {"NtDxEngGetRedirectionBitmap", {ParamTypeGeneral}},
   {"NtGdiAbortDoc", {ParamTypeGdiHandle}},
   {"NtGdiAbortPath", {ParamTypeGdiHandle}},
   {"NtGdiAddEmbFontToDC", {ParamTypeGdiHandle, ParamTypeAddress}},
   {"NtGdiAddFontMemResourceEx", {ParamTypeAddress, ParamTypeBufferSize, ParamTypeAddress, ParamTypeBufferSize, ParamTypeOutPtr}},
   {"NtGdiAddFontResourceW", {ParamTypeUnicodeStr, ParamTypeBufferSize, ParamTypeBufferSize, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiAddRemoteFontToDC", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeBufferSize, ParamTypeAddress}},
   {"NtGdiAddRemoteMMInstanceToDC", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeBufferSize}},
   {"NtGdiAlphaBlend", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress}},
   {"NtGdiAngleArc", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiAnyLinkedFonts", {ParamTypeGeneral}},
   {"NtGdiArcInternal", {ParamTypeFlag, ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiBRUSHOBJ_DeleteRbrush", {ParamTypeAddress, ParamTypeOutPtr}},
   {"NtGdiBRUSHOBJ_hGetColorTransform", {ParamTypeAddress}},
   {"NtGdiBRUSHOBJ_pvAllocRbrush", {ParamTypeAddress}},
   {"NtGdiBRUSHOBJ_pvGetRbrush", {ParamTypeAddress}},
   {"NtGdiBRUSHOBJ_ulGetBrushColor", {ParamTypeAddress}},
   {"NtGdiBeginPath", {ParamTypeGdiHandle}},
   {"NtGdiBitBlt", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiCLIPOBJ_bEnum", {ParamTypeAddress}},
   {"NtGdiCLIPOBJ_cEnumStart", {ParamTypeAddress}},
   {"NtGdiCLIPOBJ_ppoGetPath", {ParamTypeAddress}},
   {"NtGdiCancelDC", {ParamTypeGdiHandle}},
   {"NtGdiChangeGhostFont", {ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiCheckBitmapBits", {ParamTypeGdiHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiClearBitmapAttributes", {ParamTypeGdiHandle, ParamTypeFlag}},
   {"NtGdiClearBrushAttributes", {ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiCloseFigure", {ParamTypeGdiHandle}},
   {"NtGdiColorCorrectPalette", {ParamTypeGdiHandle, ParamTypeHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiCombineRgn", {ParamTypeHandle, ParamTypeHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiCombineTransform", {ParamTypeOutPtr, ParamTypeAddress, ParamTypeAddress}},
   {"NtGdiComputeXformCoefficients", {ParamTypeGdiHandle}},
   {"NtGdiConsoleTextOut", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeBufferSize, ParamTypeAddress}},
   {"NtGdiConvertMetafileRect", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiCreateBitmap", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress}},
   {"NtGdiCreateClientObj", {ParamTypeFlag}},
   {"NtGdiCreateColorSpace", {ParamTypeAddress}},
   {"NtGdiCreateColorTransform", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeAddress, ParamTypeBufferSize}},
   {"NtGdiCreateCompatibleBitmap", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiCreateCompatibleDC", {ParamTypeGdiHandle}},
   {"NtGdiCreateDIBBrush", {ParamTypeAddress, ParamTypeFlag, ParamTypeBufferSize, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress}},
   {"NtGdiCreateDIBSection", {ParamTypeGdiHandle, ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeBufferSize, ParamTypeFlag, ParamTypeBufferSize, ParamTypeOutPtr}},
   {"NtGdiCreateDIBitmapInternal", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag, ParamTypeBufferSize, ParamTypeBufferSize, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiCreateEllipticRgn", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiCreateHalftonePalette", {ParamTypeGdiHandle}},
   {"NtGdiCreateHatchBrushInternal", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiCreateMetafileDC", {ParamTypeGdiHandle}},
   {"NtGdiCreatePaletteInternal", {ParamTypeAddress, ParamTypeBufferSize}},
   {"NtGdiCreatePatternBrushInternal", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiCreatePen", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeHandle}},
   {"NtGdiCreateRectRgn", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiCreateRoundRectRgn", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiCreateServerMetaFile", {ParamTypeFlag, ParamTypeBufferSize, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiCreateSolidBrush", {ParamTypeFlag, ParamTypeHandle}},
   {"NtGdiD3dContextCreate", {ParamTypeHandle, ParamTypeHandle, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiD3dContextDestroy", {ParamTypeAddress}},
   {"NtGdiD3dContextDestroyAll", {ParamTypeAddress}},
   {"NtGdiD3dDrawPrimitives2", {ParamTypeHandle, ParamTypeHandle, ParamTypeOutPtr, ParamTypeAddress, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeRetLength}},
   {"NtGdiD3dValidateTextureStageState", {ParamTypeAddress}},
   {"NtGdiDdAddAttachedSurface", {ParamTypeHandle, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdAlphaBlt", {ParamTypeHandle, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdAttachSurface", {ParamTypeHandle, ParamTypeHandle}},
   {"NtGdiDdBeginMoCompFrame", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdBlt", {ParamTypeHandle, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdCanCreateD3DBuffer", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdCanCreateSurface", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdColorControl", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdCreateD3DBuffer", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiDdCreateDirectDrawObject", {ParamTypeGdiHandle}},
   {"NtGdiDdCreateMoComp", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdCreateSurface", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiDdCreateSurfaceEx", {ParamTypeHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiDdCreateSurfaceObject", {ParamTypeHandle, ParamTypeHandle, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag}},
   {"NtGdiDdDDICheckExclusiveOwnership", {ParamTypeGeneral}},
   {"NtGdiDdDDICheckMonitorPowerState", {ParamTypeOutPtr}},
   {"NtGdiDdDDICheckOcclusion", {ParamTypeOutPtr}},
   {"NtGdiDdDDICloseAdapter", {ParamTypeOutPtr}},
   {"NtGdiDdDDICreateAllocation", {ParamTypeOutPtr}},
   {"NtGdiDdDDICreateContext", {ParamTypeOutPtr}},
   {"NtGdiDdDDICreateDCFromMemory", {ParamTypeOutPtr}},
   {"NtGdiDdDDICreateDevice", {ParamTypeOutPtr}},
   {"NtGdiDdDDICreateOverlay", {ParamTypeOutPtr}},
   {"NtGdiDdDDICreateSynchronizationObject", {ParamTypeOutPtr}},
   {"NtGdiDdDDIDestroyAllocation", {ParamTypeOutPtr}},
   {"NtGdiDdDDIDestroyContext", {ParamTypeOutPtr}},
   {"NtGdiDdDDIDestroyDCFromMemory", {ParamTypeOutPtr}},
   {"NtGdiDdDDIDestroyDevice", {ParamTypeOutPtr}},
   {"NtGdiDdDDIDestroyOverlay", {ParamTypeOutPtr}},
   {"NtGdiDdDDIDestroySynchronizationObject", {ParamTypeOutPtr}},
   {"NtGdiDdDDIEscape", {ParamTypeOutPtr}},
   {"NtGdiDdDDIFlipOverlay", {ParamTypeOutPtr}},
   {"NtGdiDdDDIGetContextSchedulingPriority", {ParamTypeOutPtr}},
   {"NtGdiDdDDIGetDeviceState", {ParamTypeOutPtr}},
   {"NtGdiDdDDIGetDisplayModeList", {ParamTypeOutPtr}},
   {"NtGdiDdDDIGetMultisampleMethodList", {ParamTypeOutPtr}},
   {"NtGdiDdDDIGetPresentHistory", {ParamTypeOutPtr}},
   {"NtGdiDdDDIGetProcessSchedulingPriorityClass", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdDDIGetRuntimeData", {ParamTypeOutPtr}},
   {"NtGdiDdDDIGetScanLine", {ParamTypeOutPtr}},
   {"NtGdiDdDDIGetSharedPrimaryHandle", {ParamTypeOutPtr}},
   {"NtGdiDdDDIInvalidateActiveVidPn", {ParamTypeOutPtr}},
   {"NtGdiDdDDILock", {ParamTypeOutPtr}},
   {"NtGdiDdDDIOpenAdapterFromDeviceName", {ParamTypeOutPtr}},
   {"NtGdiDdDDIOpenAdapterFromGdiDisplayName", {ParamTypeOutPtr}},
   {"NtGdiDdDDIOpenAdapterFromHdc", {ParamTypeOutPtr}},
   {"NtGdiDdDDIOpenResource", {ParamTypeOutPtr}},
   {"NtGdiDdDDIPollDisplayChildren", {ParamTypeOutPtr}},
   {"NtGdiDdDDIPresent", {ParamTypeOutPtr}},
   {"NtGdiDdDDIQueryAdapterInfo", {ParamTypeOutPtr}},
   {"NtGdiDdDDIQueryAllocationResidency", {ParamTypeOutPtr}},
   {"NtGdiDdDDIQueryResourceInfo", {ParamTypeOutPtr}},
   {"NtGdiDdDDIQueryStatistics", {ParamTypeOutPtr}},
   {"NtGdiDdDDIReleaseProcessVidPnSourceOwners", {ParamTypeHandle}},
   {"NtGdiDdDDIRender", {ParamTypeOutPtr}},
   {"NtGdiDdDDISetAllocationPriority", {ParamTypeOutPtr}},
   {"NtGdiDdDDISetContextSchedulingPriority", {ParamTypeOutPtr}},
   {"NtGdiDdDDISetDisplayMode", {ParamTypeOutPtr}},
   {"NtGdiDdDDISetDisplayPrivateDriverFormat", {ParamTypeOutPtr}},
   {"NtGdiDdDDISetGammaRamp", {ParamTypeOutPtr}},
   {"NtGdiDdDDISetProcessSchedulingPriorityClass", {ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiDdDDISetQueuedLimit", {ParamTypeOutPtr}},
   {"NtGdiDdDDISetVidPnSourceOwner", {ParamTypeOutPtr}},
   {"NtGdiDdDDISharedPrimaryLockNotification", {ParamTypeOutPtr}},
   {"NtGdiDdDDISharedPrimaryUnLockNotification", {ParamTypeOutPtr}},
   {"NtGdiDdDDISignalSynchronizationObject", {ParamTypeOutPtr}},
   {"NtGdiDdDDIUnlock", {ParamTypeOutPtr}},
   {"NtGdiDdDDIUpdateOverlay", {ParamTypeOutPtr}},
   {"NtGdiDdDDIWaitForIdle", {ParamTypeOutPtr}},
   {"NtGdiDdDDIWaitForSynchronizationObject", {ParamTypeOutPtr}},
   {"NtGdiDdDDIWaitForVerticalBlankEvent", {ParamTypeOutPtr}},
   {"NtGdiDdDeleteDirectDrawObject", {ParamTypeHandle}},
   {"NtGdiDdDeleteSurfaceObject", {ParamTypeHandle}},
   {"NtGdiDdDestroyD3DBuffer", {ParamTypeHandle}},
   {"NtGdiDdDestroyMoComp", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdDestroySurface", {ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiDdEndMoCompFrame", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdFlip", {ParamTypeHandle, ParamTypeHandle, ParamTypeHandle, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdFlipToGDISurface", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdGetAvailDriverMemory", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdGetBltStatus", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdGetDC", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdGetDriverInfo", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdGetDriverState", {ParamTypeOutPtr}},
   {"NtGdiDdGetDxHandle", {ParamTypeHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiDdGetFlipStatus", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdGetInternalMoCompInfo", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdGetMoCompBuffInfo", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdGetMoCompFormats", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdGetMoCompGuids", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdGetScanLine", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdLock", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeGdiHandle}},
   {"NtGdiDdLockD3D", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdQueryDirectDrawObject", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeRetLength}},
   {"NtGdiDdQueryMoCompStatus", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdReenableDirectDrawObject", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdReleaseDC", {ParamTypeHandle}},
   {"NtGdiDdRenderMoComp", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdResetVisrgn", {ParamTypeHandle, ParamTypeWinHandle}},
   {"NtGdiDdSetColorKey", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdSetExclusiveMode", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdSetGammaRamp", {ParamTypeHandle, ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiDdSetOverlayPosition", {ParamTypeHandle, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdUnattachSurface", {ParamTypeHandle, ParamTypeHandle}},
   {"NtGdiDdUnlock", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdUnlockD3D", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdUpdateOverlay", {ParamTypeHandle, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDdWaitForVerticalBlank", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDeleteClientObj", {ParamTypeHandle}},
   {"NtGdiDeleteColorSpace", {ParamTypeHandle}},
   {"NtGdiDeleteColorTransform", {ParamTypeGdiHandle, ParamTypeHandle}},
   {"NtGdiDeleteObjectApp", {ParamTypeHandle}},
   {"NtGdiDescribePixelFormat", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeBufferSize, ParamTypeOutPtr}},
   {"NtGdiDoBanding", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiDoPalette", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiDrawEscape", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress}},
   {"NtGdiDrawStream", {ParamTypeGdiHandle}},
   {"NtGdiDvpAcquireNotification", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiDvpCanCreateVideoPort", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpColorControl", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpCreateVideoPort", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpDestroyVideoPort", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpFlipVideoPort", {ParamTypeHandle, ParamTypeHandle, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpGetVideoPortBandwidth", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpGetVideoPortConnectInfo", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpGetVideoPortField", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpGetVideoPortFlipStatus", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpGetVideoPortInputFormats", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpGetVideoPortLine", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpGetVideoPortOutputFormats", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpGetVideoSignalStatus", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDvpReleaseNotification", {ParamTypeHandle, ParamTypeHandle}},
   {"NtGdiDvpUpdateVideoPort", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiDvpWaitForVideoPortSync", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiDxgGenericThunk", {ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiEllipse", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiEnableEudc", {ParamTypeFlag}},
   {"NtGdiEndDoc", {ParamTypeGdiHandle}},
   {"NtGdiEndPage", {ParamTypeGdiHandle}},
   {"NtGdiEndPath", {ParamTypeGdiHandle}},
   {"NtGdiEngAlphaBlend", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress}},
   {"NtGdiEngAssociateSurface", {ParamTypeHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiEngBitBlt", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag}},
   {"NtGdiEngCheckAbort", {ParamTypeAddress}},
   {"NtGdiEngComputeGlyphSet", {ParamTypeGeneral}},
   {"NtGdiEngCopyBits", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress}},
   {"NtGdiEngCreateBitmap", {ParamTypeOutPtr}},
   {"NtGdiEngCreateClip", {ParamTypeGeneral}},
   {"NtGdiEngCreateDeviceBitmap", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiEngCreateDeviceSurface", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiEngCreatePalette", {ParamTypeGeneral}},
   {"NtGdiEngDeleteClip", {ParamTypeAddress}},
   {"NtGdiEngDeletePalette", {ParamTypeHandle}},
   {"NtGdiEngDeletePath", {ParamTypeAddress}},
   {"NtGdiEngDeleteSurface", {ParamTypeHandle}},
   {"NtGdiEngEraseSurface", {ParamTypeAddress, ParamTypeOutPtr}},
   {"NtGdiEngFillPath", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress}},
   {"NtGdiEngGradientFill", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeOutPtr}},
   {"NtGdiEngLineTo", {ParamTypeAddress, ParamTypeAddress, ParamTypeOutPtr}},
   {"NtGdiEngLockSurface", {ParamTypeHandle}},
   {"NtGdiEngMarkBandingSurface", {ParamTypeHandle}},
   {"NtGdiEngPaint", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeOutPtr}},
   {"NtGdiEngPlgBlt", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag}},
   {"NtGdiEngStretchBlt", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag}},
   {"NtGdiEngStretchBltROP", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag, ParamTypeAddress}},
   {"NtGdiEngStrokeAndFillPath", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress}},
   {"NtGdiEngStrokePath", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress}},
   {"NtGdiEngTextOut", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress}},
   {"NtGdiEngTransparentBlt", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress}},
   {"NtGdiEngUnlockSurface", {ParamTypeAddress}},
   {"NtGdiEnumFontChunk", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeRetLength}},
   {"NtGdiEnumFontClose", {ParamTypeFlag}},
   {"NtGdiEnumFontOpen", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiEnumObjects", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeBufferSize, ParamTypeOutPtr}},
   {"NtGdiEqualRgn", {ParamTypeHandle, ParamTypeHandle}},
   {"NtGdiEudcLoadUnloadLink", {ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiExcludeClipRect", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiExtCreatePen", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeBufferSize, ParamTypeFlag, ParamTypeHandle}},
   {"NtGdiExtCreateRegion", {ParamTypeAddress, ParamTypeBufferSize, ParamTypeOutPtr}},
   {"NtGdiExtEscape", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiExtFloodFill", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiExtGetObjectW", {ParamTypeHandle, ParamTypeBufferSize, ParamTypeOutPtr}},
   {"NtGdiExtSelectClipRgn", {ParamTypeGdiHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiExtTextOutW", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag, ParamTypeAddress, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiFONTOBJ_cGetAllGlyphHandles", {ParamTypeAddress, ParamTypeOutPtr}},
   {"NtGdiFONTOBJ_cGetGlyphs", {ParamTypeAddress}},
   {"NtGdiFONTOBJ_pQueryGlyphAttrs", {ParamTypeAddress}},
   {"NtGdiFONTOBJ_pfdg", {ParamTypeAddress}},
   {"NtGdiFONTOBJ_pifi", {ParamTypeAddress}},
   {"NtGdiFONTOBJ_pvTrueTypeFontFile", {ParamTypeAddress, ParamTypeOutPtr}},
   {"NtGdiFONTOBJ_pxoGetXform", {ParamTypeAddress}},
   {"NtGdiFONTOBJ_vGetInfo", {ParamTypeAddress}},
   {"NtGdiFillPath", {ParamTypeGdiHandle}},
   {"NtGdiFillRgn", {ParamTypeGdiHandle, ParamTypeHandle, ParamTypeHandle}},
   {"NtGdiFlattenPath", {ParamTypeGdiHandle}},
   {"NtGdiFlush", {ParamTypeGeneral}},
   {"NtGdiFontIsLinked", {ParamTypeGdiHandle}},
   {"NtGdiForceUFIMapping", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiFrameRgn", {ParamTypeGdiHandle, ParamTypeHandle, ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiFullscreenControl", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeRetLength}},
   {"NtGdiGetAndSetDCDword", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiGetAppClipBox", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiGetBitmapBits", {ParamTypeHandle, ParamTypeBufferSize, ParamTypeOutPtr}},
   {"NtGdiGetBitmapDimension", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiGetBoundsRect", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiGetCharABCWidthsW", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiGetCharSet", {ParamTypeGdiHandle}},
   {"NtGdiGetCharWidthInfo", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiGetCharWidthW", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiGetCharacterPlacementW", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiGetColorAdjustment", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiGetColorSpaceforBitmap", {ParamTypeHandle}},
   {"NtGdiGetDCDword", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiGetDCObject", {ParamTypeGdiHandle, ParamTypeFlag}},
   {"NtGdiGetDCPoint", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiGetDCforBitmap", {ParamTypeHandle}},
   {"NtGdiGetDIBitsInternal", {ParamTypeGdiHandle, ParamTypeHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag, ParamTypeBufferSize, ParamTypeBufferSize}},
   {"NtGdiGetDeviceCaps", {ParamTypeGdiHandle, ParamTypeFlag}},
   {"NtGdiGetDeviceCapsAll", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiGetDeviceGammaRamp", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiGetDeviceWidth", {ParamTypeGdiHandle}},
   {"NtGdiGetDhpdev", {ParamTypeHandle}},
   {"NtGdiGetETM", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiGetEmbUFI", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiGetEmbedFonts", {ParamTypeGeneral}},
   {"NtGdiGetEudcTimeStampEx", {ParamTypeAddress, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiGetFontData", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeBufferSize}},
   {"NtGdiGetFontFamilyInfo", {ParamTypeGdiHandle}},
   {"NtGdiGetFontResourceInfoInternalW", {ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeFlag}},
   {"NtGdiGetFontUnicodeRanges", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiGetGlyphIndicesW", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiGetGlyphIndicesWInternal", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiGetGlyphOutline", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeAddress, ParamTypeFlag}},
   {"NtGdiGetKerningPairs", {ParamTypeGdiHandle, ParamTypeBufferSize, ParamTypeOutPtr}},
   {"NtGdiGetLinkedUFIs", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiGetMiterLimit", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiGetMonitorID", {ParamTypeGdiHandle, ParamTypeBufferSize, ParamTypeOutPtr}},
   {"NtGdiGetNearestColor", {ParamTypeGdiHandle, ParamTypeFlag}},
   {"NtGdiGetNearestPaletteIndex", {ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiGetObjectBitmapHandle", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiGetOutlineTextMetricsInternalW", {ParamTypeGdiHandle, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiGetPath", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiGetPerBandInfo", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiGetPixel", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiGetRandomRgn", {ParamTypeGdiHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiGetRasterizerCaps", {ParamTypeOutPtr, ParamTypeBufferSize}},
   {"NtGdiGetRealizationInfo", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiGetRegionData", {ParamTypeHandle, ParamTypeBufferSize, ParamTypeOutPtr}},
   {"NtGdiGetRgnBox", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiGetServerMetaFileBits", {ParamTypeHandle, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiGetSpoolMessage", {ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiGetStats", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeBufferSize}},
   {"NtGdiGetStockObject", {ParamTypeFlag}},
   {"NtGdiGetStringBitmapW", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiGetSystemPaletteUse", {ParamTypeGdiHandle}},
   {"NtGdiGetTextCharsetInfo", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiGetTextExtent", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiGetTextExtentExW", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiGetTextFaceW", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiGetTextMetricsW", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeBufferSize}},
   {"NtGdiGetTransform", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiGetUFI", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiGetUFIPathname", {ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeFlag}},
   {"NtGdiGetWidthTable", {ParamTypeGdiHandle, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiGradientFill", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeFlag}},
   {"NtGdiHT_Get8BPPFormatPalette", {ParamTypeOutPtr}},
   {"NtGdiHT_Get8BPPMaskPalette", {ParamTypeOutPtr}},
   {"NtGdiHfontCreate", {ParamTypeAddress, ParamTypeBufferSize, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiIcmBrushInfo", {ParamTypeGdiHandle, ParamTypeHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiInit", {ParamTypeGeneral}},
   {"NtGdiInitSpool", {ParamTypeGeneral}},
   {"NtGdiIntersectClipRect", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiInvertRgn", {ParamTypeGdiHandle, ParamTypeHandle}},
   {"NtGdiLineTo", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiMakeFontDir", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeAddress, ParamTypeBufferSize}},
   {"NtGdiMakeInfoDC", {ParamTypeGdiHandle, ParamTypeFlag}},
   {"NtGdiMakeObjectXferable", {ParamTypeHandle}},
   {"NtGdiMaskBlt", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiMirrorWindowOrg", {ParamTypeGdiHandle}},
   {"NtGdiModifyWorldTransform", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeFlag}},
   {"NtGdiMonoBitmap", {ParamTypeHandle}},
   {"NtGdiMoveTo", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiOffsetClipRgn", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiOffsetRgn", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiOffsetViewportOrgEx", {ParamTypeGdiHandle}},
   {"NtGdiOffsetWindowOrgEx", {ParamTypeGdiHandle}},
   {"NtGdiOpenDCW", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiPATHOBJ_bEnum", {ParamTypeAddress, ParamTypeOutPtr}},
   {"NtGdiPATHOBJ_bEnumClipLines", {ParamTypeAddress}},
   {"NtGdiPATHOBJ_vEnumStart", {ParamTypeAddress}},
   {"NtGdiPATHOBJ_vEnumStartClipLines", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress}},
   {"NtGdiPATHOBJ_vGetBounds", {ParamTypeAddress, ParamTypeOutPtr}},
   {"NtGdiPatBlt", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiPathToRegion", {ParamTypeGdiHandle}},
   {"NtGdiPlgBlt", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiPolyDraw", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiPolyPatBlt", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiPolyPolyDraw", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiPolyTextOutW", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiPtInRegion", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiPtVisible", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiQueryFontAssocInfo", {ParamTypeGdiHandle}},
   {"NtGdiQueryFonts", {ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeRetLength}},
   {"NtGdiRectInRegion", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtGdiRectVisible", {ParamTypeGdiHandle, ParamTypeOutPtr}},
   {"NtGdiRectangle", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiRemoveFontMemResourceEx", {ParamTypeHandle}},
   {"NtGdiRemoveFontResourceW", {ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiRemoveMergeFont", {ParamTypeGdiHandle, ParamTypeAddress}},
   {"NtGdiResetDC", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiResizePalette", {ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiRestoreDC", {ParamTypeGdiHandle, ParamTypeFlag}},
   {"NtGdiRoundRect", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiSTROBJ_bEnum", {ParamTypeAddress, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiSTROBJ_bEnumPositionsOnly", {ParamTypeAddress, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtGdiSTROBJ_bGetAdvanceWidths", {ParamTypeAddress}},
   {"NtGdiSTROBJ_dwGetCodePage", {ParamTypeAddress}},
   {"NtGdiSTROBJ_vEnumStart", {ParamTypeAddress}},
   {"NtGdiSaveDC", {ParamTypeGdiHandle}},
   {"NtGdiScaleViewportExtEx", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiScaleWindowExtEx", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiSelectBitmap", {ParamTypeGdiHandle, ParamTypeHandle}},
   {"NtGdiSelectBrush", {ParamTypeGdiHandle, ParamTypeHandle}},
   {"NtGdiSelectClipPath", {ParamTypeGdiHandle, ParamTypeFlag}},
   {"NtGdiSelectFont", {ParamTypeGdiHandle, ParamTypeHandle}},
   {"NtGdiSelectPen", {ParamTypeGdiHandle, ParamTypeHandle}},
   {"NtGdiSetBitmapAttributes", {ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiSetBitmapBits", {ParamTypeHandle, ParamTypeBufferSize, ParamTypeAddress}},
   {"NtGdiSetBitmapDimension", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiSetBoundsRect", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeFlag}},
   {"NtGdiSetBrushAttributes", {ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiSetBrushOrg", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiSetColorAdjustment", {ParamTypeGdiHandle, ParamTypeAddress}},
   {"NtGdiSetColorSpace", {ParamTypeGdiHandle, ParamTypeHandle}},
   {"NtGdiSetDIBitsToDeviceInternal", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeBufferSize, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiSetDeviceGammaRamp", {ParamTypeGdiHandle, ParamTypeAddress}},
   {"NtGdiSetFontEnumeration", {ParamTypeFlag}},
   {"NtGdiSetFontXform", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiSetIcmMode", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiSetLayout", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiSetLinkedUFIs", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiSetMagicColors", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiSetMetaRgn", {ParamTypeGdiHandle}},
   {"NtGdiSetMiterLimit", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtGdiSetPUMPDOBJ", {ParamTypeHandle}},
   {"NtGdiSetPixel", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiSetPixelFormat", {ParamTypeGdiHandle, ParamTypeFlag}},
   {"NtGdiSetRectRgn", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiSetSizeDevice", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiSetSystemPaletteUse", {ParamTypeGdiHandle, ParamTypeFlag}},
   {"NtGdiSetTextJustification", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiSetViewportOrgEx", {ParamTypeGdiHandle}},
   {"NtGdiSetVirtualResolution", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiSetWindowOrgEx", {ParamTypeGdiHandle}},
   {"NtGdiSetupPublicCFONT", {ParamTypeGdiHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtGdiStartDoc", {ParamTypeGdiHandle, ParamTypeAddress, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtGdiStartPage", {ParamTypeGdiHandle}},
   {"NtGdiStretchBlt", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress}},
   {"NtGdiStretchDIBitsInternal", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeBufferSize, ParamTypeFlag}},
   {"NtGdiStrokeAndFillPath", {ParamTypeGdiHandle}},
   {"NtGdiStrokePath", {ParamTypeGdiHandle}},
   {"NtGdiSwapBuffers", {ParamTypeGdiHandle}},
   {"NtGdiTransformPoints", {ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiTransparentBlt", {ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeGdiHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtGdiUMPDEngFreeUserMem", {ParamTypeAddress}},
   {"NtGdiUnloadPrinterDriver", {ParamTypeAddress, ParamTypeBufferSize}},
   {"NtGdiUnmapMemFont", {ParamTypeAddress}},
   {"NtGdiUnrealizeObject", {ParamTypeHandle}},
   {"NtGdiUpdateColors", {ParamTypeGdiHandle}},
   {"NtGdiUpdateTransform", {ParamTypeGdiHandle}},
   {"NtGdiWidenPath", {ParamTypeGdiHandle}},
   {"NtGdiXFORMOBJ_bApplyXform", {ParamTypeAddress}},
   {"NtGdiXFORMOBJ_iGetXform", {ParamTypeAddress, ParamTypeOutPtr}},
   {"NtGdiXLATEOBJ_cGetPalette", {ParamTypeAddress}},
   {"NtGdiXLATEOBJ_hGetColorTransform", {ParamTypeAddress}},
   {"NtGdiXLATEOBJ_iXlate", {ParamTypeAddress}},
   {"NtUserActivateKeyboardLayout", {ParamTypeHandle, ParamTypeFlag}},
   {"NtUserAlterWindowStyle", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserAssociateInputContext", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserAttachThreadInput", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserBeginPaint", {ParamTypeWinHandle, ParamTypeOutPtr}},
   {"NtUserBitBltSysBmp", {ParamTypeGdiHandle}},
   {"NtUserBlockInput", {ParamTypeFlag}},
   {"NtUserBuildHimcList", {ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength}},
   {"NtUserBuildHwndList", {ParamTypeHandle, ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength}},
   {"NtUserBuildNameList", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength}},
   {"NtUserBuildPropList", {ParamTypeWinHandle, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeRetLength}},
   {"NtUserCalcMenuBar", {ParamTypeWinHandle}},
   {"NtUserCallHwnd", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserCallHwndLock", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserCallHwndOpt", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserCallHwndParam", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserCallHwndParamLock", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserCallMsgFilter", {ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserCallNextHookEx", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserCallNoParam", {ParamTypeFlag}},
   {"NtUserCallOneParam", {ParamTypeFlag, ParamTypeFlag}},
   {"NtUserCallTwoParam", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserChangeClipboardChain", {ParamTypeWinHandle, ParamTypeWinHandle}},
   {"NtUserChangeDisplaySettings", {ParamTypeUnicodeStr, ParamTypeOutPtr, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtUserCheckImeHotKey", {ParamTypeGeneral}},
   {"NtUserCheckMenuItem", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserChildWindowFromPointEx", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserClipCursor", {ParamTypeAddress}},
   {"NtUserCloseClipboard", {ParamTypeGeneral}},
   {"NtUserCloseDesktop", {ParamTypeHandle}},
   {"NtUserCloseWindowStation", {ParamTypeHandle}},
   {"NtUserConsoleControl", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserConvertMemHandle", {ParamTypeAddress, ParamTypeBufferSize}},
   {"NtUserCopyAcceleratorTable", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserCountClipboardFormats", {ParamTypeGeneral}},
   {"NtUserCreateAcceleratorTable", {ParamTypeAddress, ParamTypeFlag}},
   {"NtUserCreateCaret", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserCreateDesktop", {ParamTypeObjectAttr, ParamTypeUnicodeStr, ParamTypeOutPtr, ParamTypeFlag, ParamTypeAccess}},
   {"NtUserCreateInputContext", {ParamTypeFlag}},
   {"NtUserCreateLocalMemHandle", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeBufferSize, ParamTypeRetLength}},
   {"NtUserCreateWindowEx", {ParamTypeFlag, ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag, ParamTypeAddress}},
   {"NtUserCreateWindowStation", {ParamTypeObjectAttr, ParamTypeAccess, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserCtxDisplayIOCtl", {ParamTypeGeneral}},
   {"NtUserDdeGetQualityOfService", {ParamTypeWinHandle, ParamTypeWinHandle, ParamTypeOutPtr}},
   {"NtUserDdeInitialize", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserDdeSetQualityOfService", {ParamTypeWinHandle, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtUserDefSetText", {ParamTypeWinHandle, ParamTypeAddress}},
   {"NtUserDeferWindowPos", {ParamTypeHandle, ParamTypeWinHandle, ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserDeleteMenu", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserDestroyAcceleratorTable", {ParamTypeHandle}},
   {"NtUserDestroyCursor", {ParamTypeHandle, ParamTypeFlag}},
   {"NtUserDestroyInputContext", {ParamTypeHandle}},
   {"NtUserDestroyMenu", {ParamTypeHandle}},
   {"NtUserDestroyWindow", {ParamTypeWinHandle}},
   {"NtUserDisableThreadIme", {ParamTypeFlag}},
   {"NtUserDispatchMessage", {ParamTypeAddress}},
   {"NtUserDragDetect", {ParamTypeWinHandle, ParamTypeOutPtr}},
   {"NtUserDragObject", {ParamTypeWinHandle, ParamTypeWinHandle}},
   {"NtUserDrawAnimatedRects", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtUserDrawCaption", {ParamTypeWinHandle, ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserDrawCaptionTemp", {ParamTypeWinHandle, ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeGdiHandle, ParamTypeGdiHandle, ParamTypeUnicodeStr, ParamTypeFlag}},
   {"NtUserDrawIconEx", {ParamTypeGdiHandle}},
   {"NtUserDrawMenuBarTemp", {ParamTypeWinHandle, ParamTypeGdiHandle, ParamTypeOutPtr, ParamTypeHandle, ParamTypeHandle}},
   {"NtUserEmptyClipboard", {ParamTypeGeneral}},
   {"NtUserEnableMenuItem", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserEnableScrollBar", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserEndDeferWindowPosEx", {ParamTypeHandle, ParamTypeFlag}},
   {"NtUserEndMenu", {ParamTypeGeneral}},
   {"NtUserEndPaint", {ParamTypeWinHandle, ParamTypeAddress}},
   {"NtUserEnumDisplayDevices", {ParamTypeUnicodeStr, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserEnumDisplayMonitors", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeAddress, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserEnumDisplaySettings", {ParamTypeUnicodeStr, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserEvent", {ParamTypeFlag}},
   {"NtUserExcludeUpdateRgn", {ParamTypeHandle, ParamTypeWinHandle}},
   {"NtUserFillWindow", {ParamTypeWinHandle, ParamTypeWinHandle, ParamTypeGdiHandle, ParamTypeHandle}},
   {"NtUserFindExistingCursorIcon", {ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeOutPtr}},
   {"NtUserFindWindowEx", {ParamTypeWinHandle, ParamTypeWinHandle, ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeFlag}},
   {"NtUserFlashWindowEx", {ParamTypeOutPtr}},
   {"NtUserGetAltTabInfo", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserGetAncestor", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserGetAppImeLevel", {ParamTypeWinHandle}},
   {"NtUserGetAsyncKeyState", {ParamTypeFlag}},
   {"NtUserGetAtomName", {ParamTypeFlag, ParamTypeUnicodeStr}},
   {"NtUserGetCPD", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserGetCaretBlinkTime", {ParamTypeGeneral}},
   {"NtUserGetCaretPos", {ParamTypeOutPtr}},
   {"NtUserGetClassInfo", {ParamTypeHandle, ParamTypeUnicodeStr, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserGetClassName", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeUnicodeStr}},
   {"NtUserGetClipCursor", {ParamTypeOutPtr}},
   {"NtUserGetClipboardData", {ParamTypeFlag, ParamTypeOutPtr}},
   {"NtUserGetClipboardFormatName", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserGetClipboardOwner", {ParamTypeGeneral}},
   {"NtUserGetClipboardSequenceNumber", {ParamTypeGeneral}},
   {"NtUserGetClipboardViewer", {ParamTypeGeneral}},
   {"NtUserGetComboBoxInfo", {ParamTypeWinHandle, ParamTypeOutPtr}},
   {"NtUserGetControlBrush", {ParamTypeWinHandle, ParamTypeGdiHandle, ParamTypeFlag}},
   {"NtUserGetControlColor", {ParamTypeWinHandle, ParamTypeWinHandle, ParamTypeGdiHandle, ParamTypeFlag}},
   {"NtUserGetCursorFrameInfo", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength}},
   {"NtUserGetCursorInfo", {ParamTypeOutPtr}},
   {"NtUserGetDC", {ParamTypeWinHandle}},
   {"NtUserGetDCEx", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserGetDoubleClickTime", {ParamTypeGeneral}},
   {"NtUserGetForegroundWindow", {ParamTypeGeneral}},
   {"NtUserGetGUIThreadInfo", {ParamTypeFlag, ParamTypeOutPtr}},
   {"NtUserGetGuiResources", {ParamTypeHandle, ParamTypeFlag}},
   {"NtUserGetIconInfo", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserGetIconSize", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtUserGetImeHotKey", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtUserGetImeInfoEx", {ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserGetInternalWindowPos", {ParamTypeWinHandle, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtUserGetKeyNameText", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserGetKeyState", {ParamTypeFlag}},
   {"NtUserGetKeyboardLayoutList", {ParamTypeFlag, ParamTypeOutPtr}},
   {"NtUserGetKeyboardLayoutName", {ParamTypeUnicodeStr}},
   {"NtUserGetKeyboardState", {ParamTypeOutPtr}},
   {"NtUserGetLayeredWindowAttributes", {ParamTypeWinHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtUserGetListBoxInfo", {ParamTypeWinHandle}},
   {"NtUserGetMenuBarInfo", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtUserGetMenuIndex", {ParamTypeHandle, ParamTypeHandle}},
   {"NtUserGetMenuItemRect", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtUserGetMessage", {ParamTypeOutPtr, ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserGetMonitorInfo", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtUserGetMouseMovePointsEx", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserGetObjectInformation", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeRetLength}},
   {"NtUserGetOpenClipboardWindow", {ParamTypeGeneral}},
   {"NtUserGetPriorityClipboardFormat", {ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserGetProcessWindowStation", {ParamTypeGeneral}},
   {"NtUserGetRawInputBuffer", {ParamTypeOutPtr, ParamTypeRetLength, ParamTypeFlag}},
   {"NtUserGetRawInputData", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength, ParamTypeFlag}},
   {"NtUserGetRawInputDeviceInfo", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeRetLength}},
   {"NtUserGetRawInputDeviceList", {ParamTypeOutPtr, ParamTypeRetLength, ParamTypeFlag}},
   {"NtUserGetRegisteredRawInputDevices", {ParamTypeOutPtr, ParamTypeRetLength, ParamTypeFlag}},
   {"NtUserGetScrollBarInfo", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtUserGetSystemMenu", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserGetThreadDesktop", {ParamTypeFlag, ParamTypeHandle}},
   {"NtUserGetThreadState", {ParamTypeFlag}},
   {"NtUserGetTitleBarInfo", {ParamTypeWinHandle, ParamTypeOutPtr}},
   {"NtUserGetUpdateRect", {ParamTypeWinHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserGetUpdateRgn", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserGetWOWClass", {ParamTypeHandle, ParamTypeUnicodeStr}},
   {"NtUserGetWindowDC", {ParamTypeWinHandle}},
   {"NtUserGetWindowPlacement", {ParamTypeWinHandle, ParamTypeOutPtr}},
   {"NtUserHardErrorControl", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserHideCaret", {ParamTypeWinHandle}},
   {"NtUserHiliteMenuItem", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserImpersonateDdeClientWindow", {ParamTypeWinHandle, ParamTypeWinHandle}},
   {"NtUserInitTask", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserInitialize", {ParamTypeFlag, ParamTypeHandle, ParamTypeHandle}},
   {"NtUserInitializeClientPfnArrays", {ParamTypeAddress, ParamTypeAddress, ParamTypeAddress, ParamTypeHandle}},
   {"NtUserInternalGetWindowText", {ParamTypeWinHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserInvalidateRect", {ParamTypeWinHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserInvalidateRgn", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserIsClipboardFormatAvailable", {ParamTypeFlag}},
   {"NtUserKillTimer", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserLoadKeyboardLayoutEx", {ParamTypeHandle, ParamTypeFlag, ParamTypeAddress, ParamTypeHandle, ParamTypeUnicodeStr, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserLockWindowStation", {ParamTypeHandle}},
   {"NtUserLockWindowUpdate", {ParamTypeWinHandle}},
   {"NtUserLockWorkStation", {ParamTypeGeneral}},
   {"NtUserMNDragLeave", {ParamTypeGeneral}},
   {"NtUserMNDragOver", {ParamTypeFlag, ParamTypeFlag}},
   {"NtUserMapVirtualKeyEx", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeHandle}},
   {"NtUserMenuItemFromPoint", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserMessageCall", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserMinMaximize", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserModifyUserStartupInfoFlags", {ParamTypeFlag, ParamTypeFlag}},
   {"NtUserMonitorFromPoint", {ParamTypeGeneral}},
   {"NtUserMonitorFromRect", {ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserMonitorFromWindow", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserMoveWindow", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserNotifyIMEStatus", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserNotifyProcessCreate", {ParamTypeHandle, ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserNotifyWinEvent", {ParamTypeFlag, ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserOpenClipboard", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserOpenDesktop", {ParamTypeObjectAttr, ParamTypeFlag, ParamTypeAccess}},
   {"NtUserOpenInputDesktop", {ParamTypeFlag, ParamTypeFlag, ParamTypeAccess}},
   {"NtUserOpenWindowStation", {ParamTypeObjectAttr, ParamTypeAccess}},
   {"NtUserPaintDesktop", {ParamTypeHandle}},
   {"NtUserPaintMenuBar", {ParamTypeWinHandle, ParamTypeGdiHandle}},
   {"NtUserPeekMessage", {ParamTypeOutPtr, ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserPostMessage", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserPostThreadMessage", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserPrintWindow", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserProcessConnect", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserQueryInformationThread", {ParamTypeHandle, ParamTypeInfoClass, ParamTypeOutPtr, ParamTypeBufferSize}},
   {"NtUserQueryInputContext", {ParamTypeHandle, ParamTypeFlag}},
   {"NtUserQuerySendMessage", {ParamTypeFlag}},
   {"NtUserQueryWindow", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserRealChildWindowFromPoint", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserRealInternalGetMessage", {ParamTypeOutPtr, ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserRealWaitMessageEx", {ParamTypeFlag, ParamTypeTimeout}},
   {"NtUserRedrawWindow", {ParamTypeWinHandle, ParamTypeOutPtr, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserRegisterClassExWOW", {ParamTypeOutPtr, ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtUserRegisterHotKey", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserRegisterRawInputDevices", {ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserRegisterTasklist", {ParamTypeFlag}},
   {"NtUserRegisterUserApiHook", {ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserRegisterWindowMessage", {ParamTypeUnicodeStr}},
   {"NtUserRemoteConnect", {ParamTypeGeneral}},
   {"NtUserRemoteRedrawRectangle", {ParamTypeGeneral}},
   {"NtUserRemoteRedrawScreen", {ParamTypeGeneral}},
   {"NtUserRemoteStopScreenUpdates", {ParamTypeGeneral}},
   {"NtUserRemoveMenu", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserRemoveProp", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserResolveDesktop", {ParamTypeHandle, ParamTypeUnicodeStr, ParamTypeFlag, ParamTypeOutPtr}},
   {"NtUserResolveDesktopForWOW", {ParamTypeFlag}},
   {"NtUserSBGetParms", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtUserScrollDC", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtUserScrollWindowEx", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeHandle, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserSelectPalette", {ParamTypeHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserSendInput", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserSetActiveWindow", {ParamTypeWinHandle}},
   {"NtUserSetAppImeLevel", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserSetCapture", {ParamTypeWinHandle}},
   {"NtUserSetClassLong", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserSetClassWord", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserSetClipboardData", {ParamTypeFlag, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtUserSetClipboardViewer", {ParamTypeWinHandle}},
   {"NtUserSetConsoleReserveKeys", {ParamTypeFlag, ParamTypeFlag}},
   {"NtUserSetCursor", {ParamTypeHandle}},
   {"NtUserSetCursorContents", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtUserSetCursorIconData", {ParamTypeHandle, ParamTypeUnicodeStr, ParamTypeUnicodeStr, ParamTypeOutPtr}},
   {"NtUserSetFocus", {ParamTypeWinHandle}},
   {"NtUserSetImeHotKey", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserSetImeInfoEx", {ParamTypeOutPtr}},
   {"NtUserSetImeOwnerWindow", {ParamTypeWinHandle, ParamTypeWinHandle}},
   {"NtUserSetInformationProcess", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserSetInformationThread", {ParamTypeHandle, ParamTypeInfoClass, ParamTypeOutPtr, ParamTypeBufferSize}},
   {"NtUserSetInternalWindowPos", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr}},
   {"NtUserSetKeyboardState", {ParamTypeOutPtr}},
   {"NtUserSetLayeredWindowAttributes", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserSetLogonNotifyWindow", {ParamTypeWinHandle}},
   {"NtUserSetMenu", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserSetMenuContextHelpId", {ParamTypeHandle, ParamTypeFlag}},
   {"NtUserSetMenuDefaultItem", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserSetMenuFlagRtoL", {ParamTypeHandle}},
   {"NtUserSetObjectInformation", {ParamTypeHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserSetParent", {ParamTypeWinHandle, ParamTypeWinHandle}},
   {"NtUserSetProcessWindowStation", {ParamTypeHandle}},
   {"NtUserSetProp", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeHandle}},
   {"NtUserSetScrollBarInfo", {ParamTypeWinHandle}},
   {"NtUserSetScrollInfo", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserSetShellWindowEx", {ParamTypeWinHandle, ParamTypeWinHandle}},
   {"NtUserSetSysColors", {ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserSetSystemCursor", {ParamTypeHandle, ParamTypeFlag}},
   {"NtUserSetSystemMenu", {ParamTypeWinHandle, ParamTypeHandle}},
   {"NtUserSetSystemTimer", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress}},
   {"NtUserSetThreadDesktop", {ParamTypeHandle}},
   {"NtUserSetThreadLayoutHandles", {ParamTypeHandle, ParamTypeHandle}},
   {"NtUserSetThreadState", {ParamTypeFlag, ParamTypeFlag}},
   {"NtUserSetTimer", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress}},
   {"NtUserSetWinEventHook", {ParamTypeFlag, ParamTypeFlag, ParamTypeHandle, ParamTypeUnicodeStr, ParamTypeAddress, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserSetWindowFNID", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserSetWindowLong", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserSetWindowPlacement", {ParamTypeWinHandle, ParamTypeOutPtr}},
   {"NtUserSetWindowPos", {ParamTypeWinHandle, ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserSetWindowRgn", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserSetWindowStationUser", {ParamTypeHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserSetWindowWord", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserSetWindowsHookAW", {ParamTypeFlag, ParamTypeAddress, ParamTypeFlag}},
   {"NtUserSetWindowsHookEx", {ParamTypeHandle, ParamTypeUnicodeStr, ParamTypeFlag, ParamTypeFlag, ParamTypeAddress, ParamTypeFlag}},
   {"NtUserShowCaret", {ParamTypeWinHandle}},
   {"NtUserShowScrollBar", {ParamTypeWinHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserShowWindow", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserShowWindowAsync", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserSoundSentry", {ParamTypeGeneral}},
   {"NtUserSwitchDesktop", {ParamTypeHandle}},
   {"NtUserSystemParametersInfo", {ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserTestForInteractiveUser", {ParamTypeFlag}},
   {"NtUserThunkedMenuInfo", {ParamTypeHandle, ParamTypeOutPtr}},
   {"NtUserThunkedMenuItemInfo", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeUnicodeStr}},
   {"NtUserToUnicodeEx", {ParamTypeFlag, ParamTypeFlag, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag, ParamTypeHandle}},
   {"NtUserTrackMouseEvent", {ParamTypeOutPtr}},
   {"NtUserTrackPopupMenuEx", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag, ParamTypeFlag, ParamTypeWinHandle, ParamTypeOutPtr}},
   {"NtUserTranslateAccelerator", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtUserTranslateMessage", {ParamTypeOutPtr, ParamTypeFlag}},
   {"NtUserUnhookWinEvent", {ParamTypeHandle}},
   {"NtUserUnhookWindowsHookEx", {ParamTypeHandle}},
   {"NtUserUnloadKeyboardLayout", {ParamTypeHandle}},
   {"NtUserUnlockWindowStation", {ParamTypeHandle}},
   {"NtUserUnregisterClass", {ParamTypeUnicodeStr, ParamTypeHandle, ParamTypeOutPtr}},
   {"NtUserUnregisterHotKey", {ParamTypeWinHandle, ParamTypeFlag}},
   {"NtUserUnregisterUserApiHook", {ParamTypeGeneral}},
   {"NtUserUpdateInputContext", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserUpdateInstance", {ParamTypeFlag, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserUpdateLayeredWindow", {ParamTypeWinHandle, ParamTypeHandle, ParamTypeOutPtr, ParamTypeOutPtr, ParamTypeHandle, ParamTypeOutPtr, ParamTypeFlag, ParamTypeOutPtr, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserUpdatePerUserSystemParameters", {ParamTypeFlag, ParamTypeFlag}},
   {"NtUserUserHandleGrantAccess", {ParamTypeHandle, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserValidateHandleSecure", {ParamTypeHandle}},
   {"NtUserValidateRect", {ParamTypeWinHandle, ParamTypeOutPtr}},
   {"NtUserValidateTimerCallback", {ParamTypeFlag}},
   {"NtUserVkKeyScanEx", {ParamTypeFlag, ParamTypeHandle, ParamTypeFlag}},
   {"NtUserWaitForInputIdle", {ParamTypeHandle, ParamTypeFlag, ParamTypeFlag}},
   {"NtUserWaitForMsgAndEvent", {ParamTypeFlag}},
   {"NtUserWaitMessage", {ParamTypeGeneral}},
   {"NtUserWin32PoolAllocationStats", {ParamTypeGeneral}},
   {"NtUserWindowFromPoint", {ParamTypeFlag, ParamTypeFlag}},
   {"NtUserYieldTask", {ParamTypeGeneral}},

   // Terminator
   { NULL, {0} }
};
